# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df5997fbde0a6b48e83bb36b319624d4a8c11660efbd8f2b64d600c9b5d6787997dc69282184c5db798b4b93e650202b88349454dc6268522ce78a0757b6c3f8

test:
  secret_key_base: b9e56c944f46f5403e7f03fbe3a7ed739989d6ba743c0bf723c5435248087e34f979073bd7cd6cf6c2f5cc1ea8e6d610fad8f0f9841f72a06e1f844d8508feb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
